Repository AICoE/sefkhet-abwy, pull requests merged in 2019-11, with the labels that each got.

#9 requested reviewers are not @mentioned in chat
  aicoe/sesheta/review_manager.py
  aicoe/sesheta/utils.py
Labels: enhancement

#10 feature to add approved labels after approved review
  aicoe/sesheta/actions/__init__.py
  aicoe/sesheta/actions/pull_request.py
  aicoe/sesheta/label_normalizer.py
  aicoe/sesheta/review_manager.py
  pyproject.toml
Labels: approved, size/M

#11 feature to add size labels to pull requests
  .zuul.yaml
  aicoe/sesheta/actions/__init__.py
  aicoe/sesheta/actions/pull_request.py
  aicoe/sesheta/review_manager.py
  tests/needs_rebase_test.py
Labels: approved, size/L, size/M

#12 Effectively use merge_at
  aicoe/sesheta/actions/pull_request.py
  tests/needs_rebase_test.py
Labels: approved, size/S

#13 Feature: no double trouble
  Pipfile
  Pipfile.lock
  aicoe/sesheta/review_manager.py
Labels: size/L

#14 Feature: notify channel on opened/reopened issue
  aicoe/sesheta/actions/__init__.py
  aicoe/sesheta/review_manager.py
Labels: approved, size/M

#15 Feature: release handling
  aicoe/sesheta/actions/pull_request.py
  aicoe/sesheta/review_manager.py
  aicoe/sesheta/utils.py
Labels: approved, size/L

#16 Feature: chatcommand assign [WIP]
  aicoe/sesheta/chatbot.py
  aicoe/sesheta/label_normalizer.py
  aicoe/sesheta/merge_master_into_pullrequest.py
  aicoe/sesheta/review_manager.py
  aicoe/sesheta/utils.py
  chatbot
  fixtures/hangouts_chat_message.json
Labels: approved, do-not-merge/work-in-progress, enhancement, size/L

#17 supress the hangout notification on 'Automatic dependency re-locking'
  aicoe/sesheta/review_manager.py
Labels: approved, enhancement, size/S
