Repository AICoE/sefkhet-abwy, pull requests merged in 2020-11, with the labels that each got.

#87 Introduce grti and gti commands
  aicoe/sesheta/chatbot.py
Labels: size/S

#93 Release of version 0.16.0
  CHANGELOG.md
  aicoe/sesheta/__init__.py
Labels: approved, bot, size/L

#88 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#89 Automatic update of dependency aiohttp from 3.7.2 to 3.7.3
  Pipfile.lock
Labels: approved, bot, size/L

#91 Automatic update of dependency google-api-python-client from 1.12.5 to 1.12.8
  Pipfile.lock
Labels: approved, bot, size/L

#92 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#95 manage kebechet auto updates while processing
  aicoe/sesheta/review_manager.py
  aicoe/sesheta/utils.py
Labels: approved, size/S

#99 Ignore automated message from kebechet along with sesheta
  aicoe/sesheta/review_manager.py
Labels: approved, size/XS

#98 port to python 38
  .aicoe-ci.yaml
  Pipfile.lock
Labels: approved, size/M

#102 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#109 update .aicoe-ci.yaml
  .aicoe-ci.yaml
Labels: size/XS
