Repository AICoE/sefkhet-abwy, pull requests merged in 2020-12, with the labels that each got.

#112 adjust the method to gather issue related-to pull request
  aicoe/sesheta/utils.py
Labels: approved, size/XS

#114 Randomize order when reporting Thoth inhabitants
  aicoe/sesheta/chatbot.py
Labels: approved, size/XS

#117 Use ChatterBot for Sesheta
  Pipfile
  Pipfile.lock
  aicoe/sesheta/chatbot.py
Labels: approved, kind/feature, sig/cyborgs, size/L

#122 Add spacy as a dependency
  Pipfile
  Pipfile.lock
Labels: size/L

#123 Added en-core-web-sm =
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#124 Provide a custom assemble script for spacy
  .s2i/bin/assemble
Labels: approved, size/S

#126 Fixed json reponse error.
  aicoe/sesheta/chatbot.py
Labels: approved, size/XS
