Repository AICoE/sefkhet-abwy, pull requests merged in 2020-04, with the labels that each got.

#21 some dependency updates, some reformatting
  .github/CODEOWNERS
  .gitignore
  Pipfile
  Pipfile.lock
  aicoe/sesheta/__init__.py
  aicoe/sesheta/actions/common.py
  aicoe/sesheta/actions/label.py
  aicoe/sesheta/actions/pull_request.py
  aicoe/sesheta/label_normalizer.py
  aicoe/sesheta/merge_master_into_pullrequest.py
  aicoe/sesheta/review_manager.py
  aicoe/sesheta/utils.py
  fixtures/MDExOlB1bGxSZXF1ZXN0MzI2Mzk0MTkw.json
  fixtures/hangouts_chat_message.json
  fixtures/pull_request_148.json
  fixtures/pull_request_2.json
Labels: size/L

#23 removed black and pre-commit from [dev]
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#24 Added github and gchat ids for Karan Chauhan
  aicoe/sesheta/utils.py
Labels: approved, size/XS
